### ISSUE TITLE
Runtime error in malloc.c

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/reboundx#20]
@dtamayo, 

Although I'm having no issues with Python in the Jupyter notebook examples, I'm running into the following issue when attempting to compile and run `parameter_interpolation/problem.c` after pulling the changes we merged:

```bash
(rebx) stanley@PAVILION-13:~/github/sabaronett/reboundx/examples/parameter_interpolation$ make clean
...
(rebx) stanley@PAVILION-13:~/github/sabaronett/reboundx/examples/parameter_interpolation$ make
Compiling shared library librebound.so ...
...
Problem file compiled successfully.
(rebx) stanley@PAVILION-13:~/github/sabaronett/reboundx/examples/parameter_interpolation$ ./rebound
rebound: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)
```

Any ideas?

**Comment by dtamayo** [comment]
Hi Stanley,

This is difficult for me to debug because I can't reproduce the error. Do u have the lldb or gdb debuggers installed? Can u run a backtrace to see what line is causing the memory access problem?

**Comment by sabaronett** [comment]
I have gdb installed. I'm working on a backtrace for you now.

**Comment by sabaronett** [comment]
Just want to give you a heads up on time. I've setup/used GDB integrated with VS Code as a step debugger, but if it allows backtraces I don't know how to generate/capture it. I'm reading a couple of guides right now on how to use GDB straight up for backtraces, but I have a live online lecture for one of my courses in ten minutes, so I probably won't get it to you until later today. Sorry.

**Comment by dtamayo** [comment]
No problem. U can run it on the command line. If you do make clean && make to compile and then do 'gdb ./rebound', when it loads type 'run' (enter) and when it gives u the error type 'bt' (enter).

I've found similar behavior a different way which must be related so I'll also look into it from my end, but if you can send me the backtrace that would be helpful, thanks!

**Comment by sabaronett** [comment]
Here's the backtrace (sorry for the delay):
```gdb
(gdb) run
Starting program: /home/stanley/github/sabaronett/reboundx/examples/parameter_interpolation/rebound
rebound: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffffebb0801 in __GI_abort () at abort.c:79
#2  0x00007ffffec03a91 in __malloc_assert (file=<optimized out>,
    function=<optimized out>, line=<optimized out>,
    assertion=<optimized out>) at malloc.c:298
#3  sysmalloc (nb=nb@entry=64,
    av=av@entry=0x7ffffef5bc40 <main_arena>) at malloc.c:2398
#4  0x00007ffffec04ff0 in _int_malloc (
    av=av@entry=0x7ffffef5bc40 <main_arena>, bytes=bytes@entry=48)
    at malloc.c:4125
#5  0x00007ffffec070fc in __GI___libc_malloc (bytes=48)
    at malloc.c:3057
#6  0x00007fffff1e4324 in rebx_malloc (rebx=rebx@entry=0x8407810,
    memsize=memsize@entry=48) at core.c:727
#7  0x00007fffff1ec149 in rebx_init_interpolator (
    rebx=rebx@entry=0x8407810, interp=interp@entry=0x8408750,
    Nvalues=Nvalues@entry=6, times=times@entry=0x7ffffffedeb0,
    values=values@entry=0x7ffffffedee0,
    interpolation=interpolation@entry=REBX_INTERPOLATION_SPLINE)
    at interpolation.c:99
#8  0x00007fffff1ec3d1 in rebx_create_interpolator (rebx=0x8407810,
    Nvalues=6, times=0x7ffffffedeb0, values=0x7ffffffedee0,
    interpolation=REBX_INTERPOLATION_SPLINE) at interpolation.c:92
#9  0x0000000008000cd7 in main (argc=<optimized out>,
    argv=<optimized out>) at problem.c:52
```

**Comment by sabaronett** [comment]
See #23.
